import { Schema, model } from 'mongoose';

const dcpSchema = new Schema({
    cnpj: { type: String, required: true },
    nome: { type: String, required: true },
    ano: { type: Number, required: true },
    mes: { type: Number, required: true },
    trimestre: { type: Number, required: true },
    linha_1: { type: Number },
    linha_2: { type: Number },
    linha_3: { type: Number },
    linha_4: { type: Number },
    linha_5: { type: Number },
    linha_6: { type: Number },
    linha_7: { type: Number },
    linha_8: { type: Number },
    linha_9: { type: Number },
    linha_10: { type: Number },
    linha_11: { type: Number },
    linha_12: { type: Number },
    linha_13: { type: Number },
    linha_14: { type: Number },
    linha_15: { type: Number },
    linha_16: { type: Number },
    linha_17: { type: Number },
    linha_18: { type: Number },
    linha_19: { type: Number },
    linha_20: { type: Number },
    linha_21: { type: Number },
    linha_22: { type: Number },
    linha_23: { type: Number },
    linha_24: { type: Number },
    linha_25: { type: Number },
    linha_26: { type: Number },
    linha_27: { type: Number },
    linha_28: { type: Number },
    linha_29: { type: Number },
    linha_30: { type: Number },
    linha_31: { type: Number },
    linha_32: { type: Number },
    linha_33: { type: Number },
    linha_34: { type: Number },
    linha_35: { type: Number },
    linha_36: { type: Number },
    linha_37: { type: Number },
    linha_38: { type: Number },
    linha_39: { type: Number },
    linha_40: { type: Number },
    linha_41: { type: Number },
    linha_42: { type: Number },
    linha_43: { type: Number },
    linha_44: { type: Number },
    linha_45: { type: Number },
    linha_46: { type: Number },
    linha_47: { type: Number },
    linha_48: { type: Number },
    linha_49: { type: Number },
    linha_50: { type: Number },
    linha_51: { type: Number },
    linha_52: { type: Number },
    linha_53: { type: Number },
    linha_54: { type: Number },
    linha_55: { type: Number },
    linha_56: { type: Number },
    linha_57: { type: Number },
    linha_58: { type: Number },
    linha_59: { type: Number },
    linha_60: { type: Number },
    linha_61: { type: Number },
    linha_62: { type: Number },
    linha_63: { type: Number },
    linha_64: { type: Number },
    linha_65: { type: Number },
    linha_66: { type: Number },
    linha_67: { type: Number },
    linha_68: { type: Number },
    linha_69: { type: Number },
    linha_70: { type: Number },
    linha_71: { type: Number },
    linha_72: { type: Number },
    linha_73: { type: Number },
});

const DcpModel = model('Dcp', dcpSchema);

export default DcpModel;
